# Force Nixpacks to use Node.js provider
providers = ["node"]

[phases.setup]
nixpkgs = ["...", "python3"]

[phases.install]
cmds = ["npm install", "npm install -g serve"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "serve -s dist -l 8000"